# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services import sync_service_pb2 as services_dot_sync__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/sync_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SyncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFileScan = channel.unary_stream(
                '/grpc.SyncService/StreamFileScan',
                request_serializer=services_dot_sync__service__pb2.FileSyncRequest.SerializeToString,
                response_deserializer=services_dot_sync__service__pb2.FileScanChunk.FromString,
                _registered_method=True)
        self.StreamFileDownload = channel.unary_stream(
                '/grpc.SyncService/StreamFileDownload',
                request_serializer=services_dot_sync__service__pb2.FileDownloadRequest.SerializeToString,
                response_deserializer=services_dot_sync__service__pb2.FileDownloadChunk.FromString,
                _registered_method=True)


class SyncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamFileScan(self, request, context):
        """Stream file list for synchronization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFileDownload(self, request, context):
        """Stream file download
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFileScan': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFileScan,
                    request_deserializer=services_dot_sync__service__pb2.FileSyncRequest.FromString,
                    response_serializer=services_dot_sync__service__pb2.FileScanChunk.SerializeToString,
            ),
            'StreamFileDownload': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFileDownload,
                    request_deserializer=services_dot_sync__service__pb2.FileDownloadRequest.FromString,
                    response_serializer=services_dot_sync__service__pb2.FileDownloadChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.SyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.SyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamFileScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc.SyncService/StreamFileScan',
            services_dot_sync__service__pb2.FileSyncRequest.SerializeToString,
            services_dot_sync__service__pb2.FileScanChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFileDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc.SyncService/StreamFileDownload',
            services_dot_sync__service__pb2.FileDownloadRequest.SerializeToString,
            services_dot_sync__service__pb2.FileDownloadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
