# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/sync_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/sync_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bservices/sync_service.proto\x12\x04grpc\"D\n\x0f\x46ileSyncRequest\x12\x11\n\tspider_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08node_key\x18\x03 \x01(\t\"\x9d\x01\n\x08\x46ileInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\tfull_path\x18\x03 \x01(\t\x12\x11\n\textension\x18\x04 \x01(\t\x12\x0e\n\x06is_dir\x18\x05 \x01(\x08\x12\x11\n\tfile_size\x18\x06 \x01(\x03\x12\x10\n\x08mod_time\x18\x07 \x01(\x03\x12\x0c\n\x04mode\x18\x08 \x01(\r\x12\x0c\n\x04hash\x18\t \x01(\t\"g\n\rFileScanChunk\x12\x1d\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0e.grpc.FileInfo\x12\x13\n\x0bis_complete\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x13\n\x0btotal_files\x18\x04 \x01(\x05\"H\n\x13\x46ileDownloadRequest\x12\x11\n\tspider_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08node_key\x18\x03 \x01(\t\"Z\n\x11\x46ileDownloadChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bis_complete\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x13\n\x0btotal_bytes\x18\x04 \x01(\x03\x32\x99\x01\n\x0bSyncService\x12>\n\x0eStreamFileScan\x12\x15.grpc.FileSyncRequest\x1a\x13.grpc.FileScanChunk0\x01\x12J\n\x12StreamFileDownload\x12\x19.grpc.FileDownloadRequest\x1a\x17.grpc.FileDownloadChunk0\x01\x42\x08Z\x06.;grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.sync_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006.;grpc'
  _globals['_FILESYNCREQUEST']._serialized_start=37
  _globals['_FILESYNCREQUEST']._serialized_end=105
  _globals['_FILEINFO']._serialized_start=108
  _globals['_FILEINFO']._serialized_end=265
  _globals['_FILESCANCHUNK']._serialized_start=267
  _globals['_FILESCANCHUNK']._serialized_end=370
  _globals['_FILEDOWNLOADREQUEST']._serialized_start=372
  _globals['_FILEDOWNLOADREQUEST']._serialized_end=444
  _globals['_FILEDOWNLOADCHUNK']._serialized_start=446
  _globals['_FILEDOWNLOADCHUNK']._serialized_end=536
  _globals['_SYNCSERVICE']._serialized_start=539
  _globals['_SYNCSERVICE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
