version: "3.3"
services:
  master:
    image: crawlabteam/crawlab:develop
    ports:
      - "18080:8080"
    environment:
      CRAWLAB_NODE_MASTER: Y
      CRAWLAB_MONGO_HOST: mongo
    depends_on:
      - mongo

  worker:
    image: crawlabteam/crawlab:develop
    environment:
      CRAWLAB_NODE_MASTER: N
      CRAWLAB_GRPC_ADDRESS: master:9666  # grpc address
      CRAWLAB_FS_FILER_URL: http://master:8080/api/filer  # seaweedfs api
    deploy:
      replicas: 10
    depends_on:
      - master

  mongo:
    image: mongo:4.2
