name: Playwright Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      crawlab:
        image: crawlabteam/crawlab:develop
        env:
          CRAWLAB_NODE_MASTER: Y  # Y: 主节点
          CRAWLAB_MONGO_HOST: mongo  # mongo host address. 在 Docker-Compose 网络中，直接引用 service 名称
        ports:
          - 8080:8080
      mongo:
        image: mongo:5
        ports:
          - 27017:27017
    env:
      APP_URL: http://crawlab:8080
      API_ENDPOINT: http://localhost:8000
      DISPLAY_BROWSER: false
      CODING_API_ENDPOINT: https://crawlab.coding.net/open-api
      CODING_API_TOKEN: ${{ secrets.CODING_API_TOKEN }}
      CODING_API_PROJECT_NAME: crawlab
      LOG_LEVEL: info
      RETRIES: 2
      WORKERS: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
