name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      APP_URL: http://localhost:8080
      API_ENDPOINT: http://localhost:8000
      DISPLAY_BROWSER: false
      CODING_API_ENDPOINT: https://crawlab.coding.net/open-api
      CODING_API_TOKEN: ${{ secrets.CODING_API_TOKEN }}
      CODING_API_PROJECT_NAME: crawlab
      LOG_LEVEL: info
      RETRIES: 2
      WORKERS: 2
    steps:
      - uses: actions/checkout@v2
      - name: Install docker
        run: sh ./bin/install-docker.sh
      - name: Start docker
        run: |
          cd ./deploy/single-node
          docker-compose up -d
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
